# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('site_product_id', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=70)),
                ('price', models.FloatField()),
                ('stock_state', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('site_product_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('url', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.Product'),
        ),
    ]
